// <auto-generated />
using System;
using FlexFit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlexFit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325093222_Migracijaaa23")]
    partial class Migracijaaa23
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyCardFitnessObject", b =>
                {
                    b.Property<int>("DailyCardsId")
                        .HasColumnType("integer");

                    b.Property<int>("FitnessObjectsId")
                        .HasColumnType("integer");

                    b.HasKey("DailyCardsId", "FitnessObjectsId");

                    b.HasIndex("FitnessObjectsId");

                    b.ToTable("DailyCardFitnessObject");
                });

            modelBuilder.Entity("FitnessObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FitnessObjects");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.MembershipCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.ToTable("MembershipCards");

                    b.HasDiscriminator().HasValue("MembershipCard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FlexFit.Domain.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FitnessObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PremiumFee")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FitnessObjectId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("Admin");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DailyCard", b =>
                {
                    b.HasBaseType("FlexFit.Domain.Models.MembershipCard");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("MemberId");

                    b.HasDiscriminator().HasValue("DailyCard");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.SubscriptionCard", b =>
                {
                    b.HasBaseType("FlexFit.Domain.Models.MembershipCard");

                    b.Property<bool>("PersonalTrainer")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("MemberId");

                    b.HasDiscriminator().HasValue("SubscriptionCard");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.Employee", b =>
                {
                    b.HasBaseType("FlexFit.Domain.Models.User");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("integer");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.Member", b =>
                {
                    b.HasBaseType("FlexFit.Domain.Models.User");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("DailyCardFitnessObject", b =>
                {
                    b.HasOne("DailyCard", null)
                        .WithMany()
                        .HasForeignKey("DailyCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessObject", null)
                        .WithMany()
                        .HasForeignKey("FitnessObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlexFit.Domain.Models.Resource", b =>
                {
                    b.HasOne("FitnessObject", "FitnessObject")
                        .WithMany("Resources")
                        .HasForeignKey("FitnessObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessObject");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.TimeSlot", b =>
                {
                    b.HasOne("FlexFit.Domain.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("DailyCard", b =>
                {
                    b.HasOne("FlexFit.Domain.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.SubscriptionCard", b =>
                {
                    b.HasOne("FlexFit.Domain.Models.Member", "Member")
                        .WithMany("SubscriptionCards")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_MembershipCards_Users_MemberId1");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessObject", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("FlexFit.Domain.Models.Member", b =>
                {
                    b.Navigation("SubscriptionCards");
                });
#pragma warning restore 612, 618
        }
    }
}
